[tool.poetry]
name = "tdsc"
version = "0.1.0"
description = ""
authors = ["Liam Dawson <liam@ldaws.com>"]

[tool.poetry.dependencies]
python = ">=2.7,!=3.0,!=3.1,!=3.2,!=3.3,<4"
toml = "~0.9"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
